RebindableFailA: Failed with error
CallStack (from HasCallStack):
  error, called at RebindableFailA.hs:10:10 in main:Main
HasCallStack backtrace:
CallStack (from HasCallStack):
  collectBacktraces, called at libraries/ghc-internal/src/GHC/Internal/Exception.hs:89:13 in ghc-internal:GHC.Internal.Exception
  toExceptionWithBacktrace, called at libraries/ghc-internal/src/GHC/Internal/Exception.hs:125:3 in ghc-internal:GHC.Internal.Exception


